In [4]:
import numpy as np

In [5]:
t=((1,2,3,4,5))
t

(1, 2, 3, 4, 5)

In [6]:
a=np.array(t)
print(type(a))
print(a)
print(a.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5]
1


In [7]:
t=[(1,2,3,4)]
b=np.array(t)
print(b)
print(b.ndim)

[[1 2 3 4]]
2


In [8]:
t=((1,2,3),(4,5,6))

In [9]:
a=np.array(t)
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
t=((1,2,3),(4,5,6),(0,0,0))

In [11]:
a=np.array(t)
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [0 0 0]]
2


In [17]:
t=(((1,2,3),(4,5,6)),((7,8,9),(6,5,4)))

In [18]:
a=np.array(t)
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 5 4]]]
3


In [21]:
a=np.zeros(3)
print(a)
print(a.ndim)

[0. 0. 0.]
1


In [22]:
a=np.zeros((3,3))
print(a)
print(a.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [23]:
a=np.zeros((3,3,3))
print(a)
print(a.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3


In [24]:
a=np.ones(1)
print(a)
print(a.ndim)

[1.]
1
